name: Manual Full Test (Stage 0-4)

on:
  workflow_dispatch:
    inputs:
      test_description:
        description: 'テスト内容の説明'
        required: true
        default: '手動フルテスト実行'
      skip_stage4:
        description: 'Stage 4をスキップ (PRマージが必要なため)'
        type: boolean
        default: true

jobs:
  full-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Setup GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Manual Test"
        git config --global user.email "actions-manual@github.com"
        
    - name: Setup GitHub CLI Authentication
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "$GITHUB_TOKEN" | gh auth login --with-token
        
    - name: Execute Stage 0
      working-directory: tmp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "🚀 Starting Manual Full Test"
        php controllers/githubsh.php "${{ github.event.inputs.test_description }}" 0
        
    - name: Extract Issue Number
      id: extract_issue
      working-directory: tmp
      run: |
        ISSUE_URL=$(tail -n 20 githubsh.log | grep "GitHub issue created:" | tail -n 1 | awk '{print $NF}')
        ISSUE_NUMBER=$(echo $ISSUE_URL | grep -o '[0-9]*$')
        echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
        echo "Issue Number: $ISSUE_NUMBER"
        
    - name: Execute Stage 1
      working-directory: tmp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        php controllers/githubsh.php "srv-tools#${{ steps.extract_issue.outputs.issue_number }}" 1
        
    - name: Execute Stage 2
      working-directory: tmp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        php controllers/githubsh.php "srv-tools#${{ steps.extract_issue.outputs.issue_number }}" 2
        
    - name: Execute Stage 3
      working-directory: tmp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        php controllers/githubsh.php "srv-tools#${{ steps.extract_issue.outputs.issue_number }}" 3
        
    - name: Wait for Manual PR Merge (if Stage 4 enabled)
      if: ${{ github.event.inputs.skip_stage4 == 'false' }}
      run: |
        echo "⏳ Stage 4を実行するには、作成されたPull Requestを手動でマージしてください"
        echo "📋 PR確認: gh pr list --head feature/srv-tools-${{ steps.extract_issue.outputs.issue_number }}-migration*"
        echo "⚠️  このステップは手動介入が必要なため、タイムアウトします"
        sleep 300  # 5分待機
        
    - name: Execute Stage 4 (if enabled and PR merged)
      if: ${{ github.event.inputs.skip_stage4 == 'false' }}
      working-directory: tmp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        php controllers/githubsh.php "srv-tools#${{ steps.extract_issue.outputs.issue_number }}" 4
        
    - name: Generate Test Summary
      if: always()
      run: |
        echo "## 📊 Manual Full Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**テスト内容**: ${{ github.event.inputs.test_description }}" >> $GITHUB_STEP_SUMMARY
        echo "**Issue番号**: #${{ steps.extract_issue.outputs.issue_number }}" >> $GITHUB_STEP_SUMMARY
        echo "**実行日時**: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "**Stage 4実行**: ${{ github.event.inputs.skip_stage4 == 'false' && '有効' || 'スキップ' }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ **結果**: 成功" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **結果**: 失敗" >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: manual-test-reports
        path: |
          tmp/models/report/
          tmp/githubsh.log
        retention-days: 30
